name: Create Firmware Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Installing platformio'
      run: pip3 install -U platformio

    - name: 'Building a firmware for ESP32'
      run: |
        pio run
        pio run -t buildfs
# produces ${{ github.workspace }}/.pio/build/esp32dev/firmware.bin
# produces ${{ github.workspace }}/.pio/build/esp32dev/spiffs.bin

    - name: 'Upload firmware Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: ${{ github.workspace }}/.pio/build/esp32dev/firmware.bin

    - name: 'Upload spiffs Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: spiffs.bin
        path: ${{ github.workspace }}/.pio/build/esp32dev/spiffs.bin

    - name: 'Create Release'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        file: ${{ github.workspace }}/.pio/build/esp32dev/firmware.bin;${{ github.workspace }}/.pio/build/esp32dev/spiffs.bin
        body: |
          Firmware release
        draft: false
        prerelease: false

    - name: 'Upload firmware Artifact to release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/.pio/build/esp32dev/firmware.bin
        asset_name: firmware.bin

    - name: 'Upload spiffs Artifact to release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/.pio/build/esp32dev/spiffs.bin
        asset_name: spiffs.bin
